chore: pin actions (release-2.8) (#3998)
Actions need to be pinned on SHA version. Taken from
https://github.com/kumahq/kuma/blob/release-2.8/.github/workflows/lifecycle.yml

Also had to bump `actions/cache` to latest version due to
https://github.com/kumahq/kuma-gui/actions/runs/15579306770/job/43870583625?pr=3998

```sh
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```

---------

Signed-off-by: schogges <moritz.fleck@konghq.com>